In [29]:
import pandas as pd

In [32]:
bolsas_posgrad_capes_br_1995a2022 = "/Volumes/SEAGATE_EHD/sidtec_pb/pesquisa/drive_sid/bolsas_pos_graduacao_capes_brasil_1995-2022.xlsx"
bolsas_posgrad_capes_pb_1995a2022 = "/Volumes/SEAGATE_EHD/sidtec_pb/pesquisa/drive_sid/bolsas_pos_graduacao_capes_pb_1995-2022.xlsx"
cnpq_mes_doc_br_2005a2023 = "/Volumes/SEAGATE_EHD/sidtec_pb/pesquisa/drive_sid/cnpq_mestrado_doutorado_brasil_2005-2023.xlsx"
cnpq_ppq_br_2005a2023 = "/Volumes/SEAGATE_EHD/sidtec_pb/pesquisa/drive_sid/cnpq_produtividade_pesquisa_brasil_2005-2023.xlsx"
orcamento_uni = "/Volumes/SEAGATE_EHD/sidtec_pb/pesquisa/drive_sid/orçamento_universidades_2000_2023.xlsx"

In [33]:
bolsas_posgrad_capes_br_1995a2022 = pd.read_excel(bolsas_posgrad_capes_br_1995a2022)
bolsas_posgrad_capes_pb_1995a2022 = pd.read_excel(bolsas_posgrad_capes_pb_1995a2022)
cnpq_mes_doc_br_2005a2023 = pd.read_excel(cnpq_mes_doc_br_2005a2023)
cnpq_ppq_br_2005a2023 = pd.read_excel(cnpq_ppq_br_2005a2023)
# orcamento_uni = pd.read_excel(orcamento_uni)

bolsas_posgrad_capes_br_1995a2022 = bolsas_posgrad_capes_br_1995a2022.query("ANO >= 2005 and ANO <= 2022")
bolsas_posgrad_capes_br_1995a2022 = bolsas_posgrad_capes_br_1995a2022.sort_values(by = "ANO")
bolsas_posgrad_capes_pb_1995a2022 = bolsas_posgrad_capes_pb_1995a2022.query("ANO >= 2005 and ANO <= 2022")
bolsas_posgrad_capes_pb_1995a2022 = bolsas_posgrad_capes_pb_1995a2022.sort_values(by = "ANO")
cnpq_mes_doc_br_2005a2023 = cnpq_mes_doc_br_2005a2023.query("ANO >= 2005 and ANO <= 2022")
cnpq_mes_doc_br_2005a2023 = cnpq_mes_doc_br_2005a2023.sort_values(by = "ANO")
cnpq_ppq_br_2005a2023 = cnpq_ppq_br_2005a2023.query("ANO >= 2005 and ANO <= 2022")
cnpq_ppq_br_2005a2023 = cnpq_ppq_br_2005a2023.sort_values(by = "ANO")
# orcamento_uni = orcamento_uni.query("ANO >= 2005 and ANO <= 2022")

In [5]:
dict_grande_area = {"MULTIDISCIPLINAR": "CTI", "CIÊNCIAS AGRÁRIAS": "CTI", "CIÊNCIAS SOCIAIS APLICADAS": "OUTRAS",
                    "CIÊNCIAS EXATAS E DA TERRA": "CTI", "CIÊNCIAS DA SAÚDE": "CTI", "Grande Area Não Informada": "OUTRAS",
                    "CIÊNCIAS BIOLÓGICAS": "CTI", "ENGENHARIAS": "CTI", "CIÊNCIAS HUMANAS": "OUTRAS", 
                    "LINGÜÍSTICA, LETRAS E ARTES": "OUTRAS"}

In [29]:
lista_anos = list(range(2005, 2023))

In [63]:
população = "/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/POPULAÇÃO_1995A2022.xlsx"

populacao = pd.read_excel(população, dtype = int).query("ANO >= 2005")

populacao.head(3)

lista_pop_br = list(populacao["POP_BR"])
lista_pop_ne = list(populacao["POP_NE"])
lista_pop_pb = list(populacao["POP_PB"])

lista_pop_br_10k = []
lista_pop_ne_10k = []
lista_pop_pb_10k = []

lista_pop_br_100k = []
lista_pop_ne_100k = []
lista_pop_pb_100k = []

for num in lista_pop_br:
    lista_pop_br_10k.append(num / 10000)
    lista_pop_br_100k.append(num/100000)

for num in lista_pop_ne:
    lista_pop_ne_10k.append(num / 10000)
    lista_pop_ne_100k.append(num/100000)

for num in lista_pop_pb:
    lista_pop_pb_10k.append(num / 10000)
    lista_pop_pb_100k.append(num/100000)

# BOLSAS CAPES BR

In [38]:
bolsas_posgrad_capes_br_1995a2022.head(3)

,REGIAO,IDUF,NOMEMUNICIPIO,CD_MUNICIPIO_IBGE,ANO,STATUSJURIDICO,IES,NIVEL,GRANDEAREA,AREACONHECIMENTO,AREAAVALIACAO,NOMEPROGRAMA,REFERENCIAL
140290,SUL,SC,FLORIANÓPOLIS,4205407,2005,Federal,UFSC,PÓS-DOUTORADO,CIÊNCIAS HUMANAS,ANTROPOLOGIA,ANTROPOLOGIA / ARQUEOLOGIA,ANTROPOLOGIA SOCIAL,1
137132,SUDESTE,SP,SÃO CARLOS,3548906,2005,Estadual,USP/SC,MESTRADO,Grande Area Não Informada,Área Não Informada,INDEFINIDA,NaN,7
137133,CENTRO-OESTE,DF,BRASÍLIA,5300108,2005,Federal,UNB,DOUTORADO PLENO,CIÊNCIAS HUMANAS,HISTÓRIA,HISTÓRIA,HISTÓRIA,7

In [39]:
bolsas_posgrad_capes_br_1995a2022["CTI"] = bolsas_posgrad_capes_br_1995a2022["GRANDEAREA"].map(dict_grande_area)
bolsas_posgrad_capes_br_1995a2022.head(5)

,REGIAO,IDUF,NOMEMUNICIPIO,CD_MUNICIPIO_IBGE,ANO,STATUSJURIDICO,IES,NIVEL,GRANDEAREA,AREACONHECIMENTO,AREAAVALIACAO,NOMEPROGRAMA,REFERENCIAL,CTI
140290,SUL,SC,FLORIANÓPOLIS,4205407,2005,Federal,UFSC,PÓS-DOUTORADO,CIÊNCIAS HUMANAS,ANTROPOLOGIA,ANTROPOLOGIA / ARQUEOLOGIA,ANTROPOLOGIA SOCIAL,1,OUTRAS
137132,SUDESTE,SP,SÃO CARLOS,3548906,2005,Estadual,USP/SC,MESTRADO,Grande Area Não Informada,Área Não Informada,INDEFINIDA,NaN,7,OUTRAS
137133,CENTRO-OESTE,DF,BRASÍLIA,5300108,2005,Federal,UNB,DOUTORADO PLENO,CIÊNCIAS HUMANAS,HISTÓRIA,HISTÓRIA,HISTÓRIA,7,OUTRAS
137134,SUDESTE,SP,CAMPINAS,3509502,2005,Estadual,UNICAMP,MESTRADO,CIÊNCIAS AGRÁRIAS,CIÊNCIA E TECNOLOGIA DE ALIMENTOS,CIÊNCIA DE ALIMENTOS,CIÊNCIA DE ALIMENTOS,7,CTI
137135,SUL,PR,CURITIBA,4106902,2005,Federal,UFPR,DOUTORADO PLENO,CIÊNCIAS BIOLÓGICAS,ZOOLOGIA,CIÊNCIAS BIOLÓGICAS I,ZOOLOGIA,7,CTI

In [40]:
bolsas_posgrad_capes_br_1995a2022.query("ANO == 2005 and CTI == 'CTI'")["REFERENCIAL"].sum()

18319

In [41]:
lista_CTI_br = []
for i in range(min(list(bolsas_posgrad_capes_br_1995a2022["ANO"].unique())), 
               max(list(bolsas_posgrad_capes_br_1995a2022["ANO"].unique())) + 1):
    dados = bolsas_posgrad_capes_br_1995a2022.query(f"ANO == {i}")
    dados = dados.query("CTI == 'CTI'")
    total = dados["REFERENCIAL"].sum()
    lista_CTI_br.append(total)

lista_outras_br = []
for i in range(min(list(bolsas_posgrad_capes_br_1995a2022["ANO"].unique())), 
               max(list(bolsas_posgrad_capes_br_1995a2022["ANO"].unique())) + 1):
    dados = bolsas_posgrad_capes_br_1995a2022.query(f"ANO == {i}")
    dados = dados.query("CTI == 'OUTRAS'")
    total = dados["REFERENCIAL"].sum()
    lista_outras_br.append(total)

In [39]:
lista_CTI_br

[18319,
 20951,
 21014,
 27861,
 32923,
 40891,
 51615,
 55680,
 60340,
 63777,
 66649,
 64913,
 67037,
 67131,
 63548,
 67177,
 65646,
 65221]

In [42]:
bolsas_posgrad_capes_br_1995a2022.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/capes_br.xlsx", index = False)

# BOLSAS CAPES PB

In [5]:
bolsas_posgrad_capes_pb_1995a2022.head(3)

,REGIAO,IDUF,NOMEMUNICIPIO,CD_MUNICIPIO_IBGE,ANO,STATUSJURIDICO,IES,NIVEL,GRANDEAREA,AREACONHECIMENTO,AREAAVALIACAO,NOMEPROGRAMA,REFERENCIAL
0,NORDESTE,PB,AREIA,2501104,2022,Federal,UFPB/AREIA,DOUTORADO PLENO,CIÊNCIAS AGRÁRIAS,AGRONOMIA,CIÊNCIAS AGRÁRIAS I,AGRONOMIA,61
1,NORDESTE,PB,CAMPINA GRANDE,2504009,2022,Federal,UFCG,DOUTORADO PLENO,CIÊNCIAS AGRÁRIAS,ENGENHARIA AGRÍCOLA,CIÊNCIAS AGRÁRIAS I,ENGENHARIA AGRÍCOLA,46
2,NORDESTE,PB,AREIA,2501104,2022,Federal,UFPB/AREIA,MESTRADO,CIÊNCIAS AGRÁRIAS,AGRONOMIA,CIÊNCIAS AGRÁRIAS I,AGRONOMIA,40

In [40]:
bolsas_posgrad_capes_pb_1995a2022["CTI"] = bolsas_posgrad_capes_pb_1995a2022["GRANDEAREA"].map(dict_grande_area)
bolsas_posgrad_capes_pb_1995a2022.head(5)

,REGIAO,IDUF,NOMEMUNICIPIO,CD_MUNICIPIO_IBGE,ANO,STATUSJURIDICO,IES,NIVEL,GRANDEAREA,AREACONHECIMENTO,AREAAVALIACAO,NOMEPROGRAMA,REFERENCIAL,CTI
3868,NORDESTE,PB,CAMPINA GRANDE,2504009,2005,Federal,UFCG,DOUTORADO PLENO,ENGENHARIAS,ENGENHARIA DE MINAS,ENGENHARIAS II,ENGENHARIA MINERAL,1,CTI
3771,NORDESTE,PB,CAMPINA GRANDE,2504009,2005,Federal,UFCG,MESTRADO,CIÊNCIAS AGRÁRIAS,MEDICINA VETERINÁRIA,MEDICINA VETERINÁRIA,MEDICINA VETERINÁRIA,4,CTI
3770,NORDESTE,PB,JOÃO PESSOA,2507507,2005,Federal,UFPB/J.P.,DOUTORADO PLENO,Grande Area Não Informada,Área Não Informada,INDEFINIDA,NaN,5,OUTRAS
3769,NORDESTE,PB,CAMPINA GRANDE,2504009,2005,Federal,UFCG,DOUTORADO PLENO,CIÊNCIAS EXATAS E DA TERRA,MATEMÁTICA,MATEMÁTICA / PROBABILIDADE E ESTATÍSTICA,MATEMÁTICA,5,CTI
3768,NORDESTE,PB,JOÃO PESSOA,2507507,2005,Federal,UFPB/J.P.,MESTRADO,CIÊNCIAS DA SAÚDE,ENFERMAGEM,ENFERMAGEM,ENFERMAGEM,5,CTI

In [47]:
bolsas_posgrad_capes_pb_1995a2022.query("ANO == 2005 and CTI == 'CTI'")["REFERENCIAL"].sum()

467

In [45]:
lista_CTI_pb = []
for i in range(min(list(bolsas_posgrad_capes_pb_1995a2022["ANO"].unique())), max(list(bolsas_posgrad_capes_pb_1995a2022["ANO"].unique())) + 1):
    dados = bolsas_posgrad_capes_pb_1995a2022.query(f"ANO == {i}")
    dados = dados.query("CTI == 'CTI'")
    total = dados["REFERENCIAL"].sum()
    lista_CTI_pb.append(total)

lista_outras_pb = []
for i in range(min(list(bolsas_posgrad_capes_pb_1995a2022["ANO"].unique())), max(list(bolsas_posgrad_capes_pb_1995a2022["ANO"].unique())) + 1):
    dados = bolsas_posgrad_capes_pb_1995a2022.query(f"ANO == {i}")
    dados = dados.query("CTI == 'OUTRAS'")
    total = dados["REFERENCIAL"].sum()
    lista_outras_pb.append(total)

In [46]:
lista_CTI_pb

[467,
 511,
 542,
 761,
 1124,
 1453,
 1860,
 1938,
 1921,
 1909,
 1936,
 1891,
 2059,
 2107,
 1958,
 1827,
 1705,
 1566]

In [ ]:
bolsas_posgrad_capes_pb_1995a2022.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/capes_pb.xlsx", index = False)

# BOLSAS CAPES NORDESTE

In [44]:
bolsas_posgrad_capes_ne_1995a2022 = pd.read_excel("/Volumes/SEAGATE_EHD/sidtec_pb/pesquisa/drive_sid/bolsas_pos_graduacao_capes_brasil_1995-2022.xlsx")
bolsas_posgrad_capes_ne_1995a2022 = bolsas_posgrad_capes_ne_1995a2022.query("REGIAO == 'NORDESTE'")
bolsas_posgrad_capes_ne_1995a2022 = bolsas_posgrad_capes_ne_1995a2022.query("ANO >= 2005 and ANO <= 2022")
bolsas_posgrad_capes_ne_1995a2022 = bolsas_posgrad_capes_ne_1995a2022.sort_values(by = "ANO")

bolsas_posgrad_capes_ne_1995a2022.index = range(bolsas_posgrad_capes_ne_1995a2022.shape[0])

bolsas_posgrad_capes_ne_1995a2022.head(3)

,REGIAO,IDUF,NOMEMUNICIPIO,CD_MUNICIPIO_IBGE,ANO,STATUSJURIDICO,IES,NIVEL,GRANDEAREA,AREACONHECIMENTO,AREAAVALIACAO,NOMEPROGRAMA,REFERENCIAL
0,NORDESTE,SE,SÃO CRISTÓVÃO,2806701,2005,Federal,FUFSE,DOUTORADO PLENO,CIÊNCIAS HUMANAS,CIÊNCIA POLÍTICA,CIÊNCIA POLÍTICA E RELAÇÕES INTERNACIONAIS,CIÊNCIA POLÍTICA,1
1,NORDESTE,RN,NATAL,2408102,2005,Federal,UFRN,MESTRADO,CIÊNCIAS DA SAÚDE,NUTRIÇÃO,MEDICINA II,CIÊNCIAS DA SAÚDE,4
2,NORDESTE,CE,FORTALEZA,2304400,2005,Federal,UFC,MESTRADO,CIÊNCIAS DA SAÚDE,GINECOLOGIA E OBSTETRÍCIA,MEDICINA III,TOCO-GINECOLOGIA,4

In [45]:
bolsas_posgrad_capes_ne_1995a2022["CTI"] = bolsas_posgrad_capes_ne_1995a2022["GRANDEAREA"].map(dict_grande_area)
bolsas_posgrad_capes_ne_1995a2022.head(5)

,REGIAO,IDUF,NOMEMUNICIPIO,CD_MUNICIPIO_IBGE,ANO,STATUSJURIDICO,IES,NIVEL,GRANDEAREA,AREACONHECIMENTO,AREAAVALIACAO,NOMEPROGRAMA,REFERENCIAL,CTI
0,NORDESTE,SE,SÃO CRISTÓVÃO,2806701,2005,Federal,FUFSE,DOUTORADO PLENO,CIÊNCIAS HUMANAS,CIÊNCIA POLÍTICA,CIÊNCIA POLÍTICA E RELAÇÕES INTERNACIONAIS,CIÊNCIA POLÍTICA,1,OUTRAS
1,NORDESTE,RN,NATAL,2408102,2005,Federal,UFRN,MESTRADO,CIÊNCIAS DA SAÚDE,NUTRIÇÃO,MEDICINA II,CIÊNCIAS DA SAÚDE,4,CTI
2,NORDESTE,CE,FORTALEZA,2304400,2005,Federal,UFC,MESTRADO,CIÊNCIAS DA SAÚDE,GINECOLOGIA E OBSTETRÍCIA,MEDICINA III,TOCO-GINECOLOGIA,4,CTI
3,NORDESTE,RN,MOSSORÓ,2408003,2005,Estadual,UERN,MESTRADO,MULTIDISCIPLINAR,INTERDISCIPLINAR,INTERDISCIPLINAR,DESENVOLVIMENTO E MEIO AMBIENTE,4,CTI
4,NORDESTE,CE,FORTALEZA,2304400,2005,Federal,UFC,MESTRADO,CIÊNCIAS AGRÁRIAS,CIÊNCIA DO SOLO,CIÊNCIAS AGRÁRIAS I,Ciência do Solo,5,CTI

In [51]:
bolsas_posgrad_capes_ne_1995a2022.query("ANO == 2005 and CTI == 'CTI'")["REFERENCIAL"].sum()

2507

In [46]:
lista_CTI_ne = []
for i in range(min(list(bolsas_posgrad_capes_ne_1995a2022["ANO"].unique())), max(list(bolsas_posgrad_capes_ne_1995a2022["ANO"].unique())) + 1):
    dados = bolsas_posgrad_capes_ne_1995a2022.query(f"ANO == {i}")
    dados = dados.query("CTI == 'CTI'")
    total = dados["REFERENCIAL"].sum()
    lista_CTI_ne.append(total)

lista_outras_ne = []
for i in range(min(list(bolsas_posgrad_capes_ne_1995a2022["ANO"].unique())), max(list(bolsas_posgrad_capes_ne_1995a2022["ANO"].unique())) + 1):
    dados = bolsas_posgrad_capes_ne_1995a2022.query(f"ANO == {i}")
    dados = dados.query("CTI == 'OUTRAS'")
    total = dados["REFERENCIAL"].sum()
    lista_outras_ne.append(total)

In [53]:
lista_CTI_ne

[2507,
 3192,
 3370,
 4615,
 6352,
 8095,
 10392,
 11069,
 11479,
 11668,
 11999,
 11607,
 12183,
 12103,
 11421,
 11621,
 11717,
 12073]

# BOLSAS CNPQ MESTRADO E DOUTORADO

In [8]:
cnpq_mes_doc_br_2005a2023.head(3)

,INSTITUICAO,AREACONHECIMENTO,NIVEL,CATEGORIA_NIVEL,GRANDEAREA,LINHAFORMENTO,ORIGEMRECURSO,REGIAO,IDUF,NOMEMUNICIPIO,CD_MUNICIPIO_IBGE,BENEFICIARIO_ANO,BOLSA_ANO,AUXILIO_ANO,ANO
0,Aalto University School of Art and Design,PROGRAMA DE ACAO INDUZIDA PARA FORMACAO NO EXT...,Doutorado no Exterior,NaN,Ciências Sociais Aplicadas,BOLSAS DE FORMAÇÃO E DE PESQUISADORES,CNPq,Exterior,\EX,Exterior,NaN,1.0,1.00,0,2005
7148,Universidade Federal de Santa Catarina,Programas Regulares,Pós-Doutorado,NaN,Ciências Exatas e da Terra,BOLSAS DE FORMAÇÃO E DE PESQUISADORES,CNPq,Sul,SC,Florianopolis,4205407.0,2.0,1.25,0,2005
7149,Universidade Federal de Santa Catarina,Programas Regulares,Pós-Doutorado,NaN,Ciências Exatas e da Terra,BOLSAS DE FORMAÇÃO E DE PESQUISADORES,CNPq,Sul,SC,Florianopolis,4205407.0,2.0,0.50,0,2005

In [9]:
cnpq_mes_doc_br_2005a2023["NIVEL"].unique()

array(['Doutorado no Exterior', 'Pós-Doutorado', 'Doutorado', 'Mestrado',
       'Doutorado Sanduíche', 'Fixação de Doutores/Recém-Doutor',
       'Doutorado Sanduíche no Exterior', 'Pós-Doutorado Exterior',
       'Pós-Doutorado Empresarial', 'Doutorado Sanduíche Empresarial',
       'Mestrado Profissional no Exterior'], dtype=object)

In [7]:
cnpq_mes_doc_br_2005a2023.query(r"IDUF == '\\NI'")

,INSTITUICAO,AREACONHECIMENTO,NIVEL,CATEGORIA_NIVEL,GRANDEAREA,LINHAFORMENTO,ORIGEMRECURSO,REGIAO,IDUF,NOMEMUNICIPIO,CD_MUNICIPIO_IBGE,BENEFICIARIO_ANO,BOLSA_ANO,AUXILIO_ANO,ANO
11786,Não informada,Programas Regulares,Pós-Doutorado,NaN,"Lingüística, Letras e Artes",BOLSAS DE FORMAÇÃO E DE PESQUISADORES,CNPq,Não informada,\NI,Não informada,NaN,1.0,0.25,0,2006
22998,Não informada,Programas Regulares,Pós-Doutorado,NaN,"Lingüística, Letras e Artes",BOLSAS DE FORMAÇÃO E DE PESQUISADORES,CNPq,Não informada,\NI,Não informada,NaN,1.0,0.75,0,2007

In [71]:
lista_mes_doc_cnpq_br = []
for i in range(min(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())), max(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())) + 1):
    dados = cnpq_mes_doc_br_2005a2023.query(f"ANO == {i} and REGIAO != 'Exterior'")
    lista_mes_doc_cnpq_br.append(dados.shape[0])

lista_mes_doc_cnpq_ne = []
for i in range(min(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())), max(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())) + 1):
    dados = cnpq_mes_doc_br_2005a2023.query(f"ANO == {i} and REGIAO == 'Nordeste'")
    lista_mes_doc_cnpq_ne.append(dados.shape[0])

lista_mes_doc_cnpq_pb = []
for i in range(min(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())), max(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())) + 1):
    dados = cnpq_mes_doc_br_2005a2023.query(f"ANO == {i} and IDUF == 'PB'")
    lista_mes_doc_cnpq_pb.append(dados.shape[0])

# BOLSAS CNPQ PPQ

In [6]:
cnpq_ppq_br_2005a2023.head(3)

,INSTITUICAO,AREACONHECIMENTO,NIVEL,CATEGORIA_NIVEL,GRANDEAREA,LINHAFORMENTO,ORIGEMRECURSO,REGIAO,IDUF,NOMEMUNICIPIO,CD_MUNICIPIO_IBGE,BENEFICIARIO_ANO,BOLSA_ANO,AUXILIO_ANO,ANO
0,Arquivo Nacional,Programas Regulares,Produtividade em Pesquisa,1C,"Lingüística, Letras e Artes",BOLSAS DE FORMAÇÃO E DE PESQUISADORES,CNPq,Sudeste,RJ,Rio de Janeiro,3304557.0,0.5,0.83,0,2005
5766,Universidade Federal de Santa Catarina,Programas Regulares,Produtividade em Pesquisa,1D,Engenharias,BOLSAS DE FORMAÇÃO E DE PESQUISADORES,CNPq,Sul,SC,Florianopolis,4205407.0,1.0,1.00,0,2005
5765,Universidade Federal de Santa Catarina,Programas Regulares,Produtividade em Pesquisa,1D,Engenharias,BOLSAS DE FORMAÇÃO E DE PESQUISADORES,CNPq,Sul,SC,Florianopolis,4205407.0,0.5,0.83,0,2005

In [72]:
cnpq_ppq_br_2005a2023["REGIAO"].unique()

array(['Sudeste', 'Sul', 'Nordeste', 'Norte', 'Centro-Oeste'],
      dtype=object)

In [73]:
lista_pq_cnpq_br = []
for i in range(min(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())), max(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())) + 1):
    dados = cnpq_ppq_br_2005a2023.query(f"ANO == {i} and REGIAO != 'Exterior'")
    lista_pq_cnpq_br.append(dados.shape[0])

lista_pq_cnpq_ne = []
for i in range(min(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())), max(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())) + 1):
    dados = cnpq_ppq_br_2005a2023.query(f"ANO == {i} and REGIAO == 'Nordeste'")
    lista_pq_cnpq_ne.append(dados.shape[0])

lista_pq_cnpq_pb = []
for i in range(min(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())), max(list(cnpq_mes_doc_br_2005a2023["ANO"].unique())) + 1):
    dados = cnpq_ppq_br_2005a2023.query(f"ANO == {i} and IDUF == 'PB'")
    lista_pq_cnpq_pb.append(dados.shape[0])

In [51]:
dados = pd.read_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/new_data.xlsx")

dados.columns

Index(['ANO', 'POP_BR', 'POP_BR_10K', 'POP_BR_100K', 'POP_PB', 'POP_PB_10K',
       'POP_PB_100K', 'POP_NE', 'POP_NE_10K', 'POP_NE_100K', 'CAPES_CTI_BR',
       'CAPES_OUTRAS_BR', 'CAPES_CTI_PB', 'CAPES_OUTRAS_PB', 'CAPES_CTI_NE',
       'CAPES_OUTRAS_NE', 'CNPQ_MES_DOC_BR', 'CNPQ_MES_DOC_PB',
       'CNPQ_MES_DOC_NE', 'CNPQ_PQ_BR', 'CNPQ_PQ_PB', 'CNPQ_PQ_NE',
       'cti/outras_br', 'cti/outras_pb', 'cti/outras_ne'],
      dtype='object')

In [11]:
colunas_br = ['ANO', 'POP_BR', 'POP_BR_10K', 'POP_BR_100K', 'POP_PB', 'POP_PB_10K',
       'POP_PB_100K', 'POP_NE', 'POP_NE_10K', 'POP_NE_100K', 'CAPES_CTI_BR',
       'CAPES_OUTRAS_BR', 'CNPQ_MES_DOC_BR', 'CNPQ_PQ_BR']

colunas_pb = ['ANO', 'POP_BR', 'POP_BR_10K', 'POP_BR_100K', 'POP_PB', 'POP_PB_10K',
       'POP_PB_100K', 'POP_NE', 'POP_NE_10K', 'POP_NE_100K', 'CAPES_CTI_PB', 'CAPES_OUTRAS_PB',
       'CNPQ_MES_DOC_PB', 'CNPQ_PQ_PB']

colunas_ne = ['ANO', 'POP_BR', 'POP_BR_10K', 'POP_BR_100K', 'POP_PB', 'POP_PB_10K',
       'POP_PB_100K', 'POP_NE', 'POP_NE_10K', 'POP_NE_100K', 'CAPES_CTI_NE',
       'CAPES_OUTRAS_NE','CNPQ_MES_DOC_NE', 'CNPQ_PQ_NE']

In [14]:
dados["cti/outras_br"] = dados["CAPES_CTI_BR"] / dados["CAPES_OUTRAS_BR"]
dados["cti/outras_pb"] = dados["CAPES_CTI_PB"] / dados["CAPES_OUTRAS_PB"]
dados["cti/outras_ne"] = dados["CAPES_CTI_NE"] / dados["CAPES_OUTRAS_NE"]

In [17]:
dados.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/new_data.xlsx", index = False)

# APLICAÇÃO AJUSTES

In [47]:
bolsas_posgrad_capes_br_1995a2022.groupby(by = ["GRANDEAREA"])["REFERENCIAL"].sum().to_frame()

                             REFERENCIAL
GRANDEAREA
CIÊNCIAS AGRÁRIAS                 179024
CIÊNCIAS BIOLÓGICAS               137643
CIÊNCIAS DA SAÚDE                 189234
CIÊNCIAS EXATAS E DA TERRA        151810
CIÊNCIAS HUMANAS                  192023
CIÊNCIAS SOCIAIS APLICADAS        111987
ENGENHARIAS                       144907
Grande Area Não Informada          78349
LINGÜÍSTICA, LETRAS E ARTES        70614
MULTIDISCIPLINAR                  118075

In [49]:
total_grande_area_br = bolsas_posgrad_capes_br_1995a2022.groupby(by = ["GRANDEAREA"])["REFERENCIAL"].sum().to_frame()
total_grande_area_pb = bolsas_posgrad_capes_pb_1995a2022.groupby(by = ["GRANDEAREA"])["REFERENCIAL"].sum().to_frame()
total_grande_area_ne = bolsas_posgrad_capes_ne_1995a2022.groupby(by = ["GRANDEAREA"])["REFERENCIAL"].sum().to_frame()

total_grande_area_br_df = bolsas_posgrad_capes_br_1995a2022.groupby(by = ["ANO", "GRANDEAREA"])["REFERENCIAL"].sum().to_frame()
total_grande_area_pb_df = bolsas_posgrad_capes_pb_1995a2022.groupby(by = ["ANO", "GRANDEAREA"])["REFERENCIAL"].sum().to_frame()
total_grande_area_ne_df = bolsas_posgrad_capes_ne_1995a2022.groupby(by = ["ANO", "GRANDEAREA"])["REFERENCIAL"].sum().to_frame()

total_grande_area_br.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/grande_area_br.xlsx")
total_grande_area_ne.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/grande_area_ne.xlsx")
total_grande_area_pb.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/grande_area_pb.xlsx")

total_grande_area_br_df.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/grande_area_br_df.xlsx")
total_grande_area_ne_df.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/grande_area_ne_df.xlsx")
total_grande_area_pb_df.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/grande_area_pb_df.xlsx")

In [52]:
dados["bolsas/pop10_BR"] = dados["CAPES_CTI_BR"] / dados["POP_BR_10K"]
dados["bolsas/pop10_PB"] = dados["CAPES_CTI_PB"] / dados["POP_PB_10K"]
dados["bolsas/pop10_NE"] = dados["CAPES_CTI_NE"] / dados["POP_NE_10K"]

dados["bolsas/pop100_BR"] = dados["CAPES_CTI_BR"] / dados["POP_BR_100K"]
dados["bolsas/pop100_PB"] = dados["CAPES_CTI_PB"] / dados["POP_PB_100K"]
dados["bolsas/pop100_NE"] = dados["CAPES_CTI_NE"] / dados["POP_NE_100K"]

dados

,ANO,POP_BR,POP_BR_10K,POP_BR_100K,POP_PB,POP_PB_10K,POP_PB_100K,POP_NE,POP_NE_10K,POP_NE_100K,...,CNPQ_PQ_NE,cti/outras_br,cti/outras_pb,cti/outras_ne,bolsas/pop10_BR,bolsas/pop10_PB,bolsas/pop10_NE,bolsas/pop100_BR,bolsas/pop100_PB,bolsas/pop100_NE
0,2005,180173245,18017.3245,1801.73245,3602935,360.2935,36.02935,50387601,5038.7601,503.87601,...,940,1.912812,2.370558,1.835286,1.016744,1.296165,0.497543,10.167436,12.961655,4.975430
1,2006,182289756,18228.9756,1822.89756,3635654,363.5654,36.35654,50926471,5092.6471,509.26471,...,885,1.862642,2.433333,1.987547,1.149324,1.405524,0.626786,11.493240,14.055243,6.267860
2,2007,184406267,18440.6267,1844.06267,3668372,366.8372,36.68372,51465340,5146.5340,514.65340,...,1046,1.900687,2.474886,1.966161,1.139549,1.477495,0.654810,11.395491,14.774946,6.548096
3,2008,186522777,18652.2777,1865.22777,3701091,370.1091,37.01091,52004210,5200.4210,520.04210,...,1888,1.928898,2.143662,1.922917,1.493705,2.056150,0.887428,14.937050,20.561505,8.874282
4,2009,188639288,18863.9288,1886.39288,3733809,373.3809,37.33809,52543080,5254.3080,525.43080,...,1627,2.313633,1.908319,2.192613,1.745289,3.010331,1.208913,17.452886,30.103307,12.089128
5,2010,190755799,19075.5799,1907.55799,3766527,376.6527,37.66527,53081950,5308.1950,530.81950,...,1727,2.375174,2.012465,2.231257,2.143631,3.857665,1.525000,21.436308,38.576652,15.250005
6,2011,191781358,19178.1358,1917.81358,3783874,378.3874,37.83874,53212169,5321.2169,532.12169,...,1692,2.523221,2.017354,2.410019,2.691346,4.915597,1.952937,26.913460,49.155971,19.529367
7,2012,192806917,19280.6917,1928.06917,3801221,380.1221,38.01221,53342388,5334.2388,533.42388,...,1471,2.505400,2.079399,2.568809,2.887863,5.098362,2.075085,28.878632,50.983618,20.750852
8,2013,193832477,19383.2477,1938.32477,3818567,381.8567,38.18567,53472608,5347.2608,534.72608,...,1652,2.207184,1.948276,2.345525,3.112997,5.030683,2.146707,31.129974,50.306830,21.467066
9,2014,194858036,19485.8036,1948.58036,3835914,383.5914,38.35914,53602827,5360.2827,536.02827,...,1571,1.517994,1.512678,1.412591,3.272998,4.976650,2.176751,32.729982,49.766496,21.767509
10,2015,195883596,19588.3596,1958.83596,3853260,385.3260,38.53260,53733046,5373.3046,537.33046,...,1589,1.717713,1.541401,1.657092,3.402480,5.024317,2.233076,34.024799,50.243171,22.330765
11,2016,196909155,19690.9155,1969.09155,3870607,387.0607,38.70607,53863266,5386.3266,538.63266,...,3068,1.827506,1.725365,1.923281,3.296596,4.885539,2.154901,32.965963,48.855386,21.549009
12,2017,197934714,19793.4714,1979.34714,3887954,388.7954,38.87954,53993485,5399.3485,539.93485,...,2400,1.952439,1.817299,2.051355,3.386824,5.295845,2.256383,33.868238,52.958445,22.563833
13,2018,198960274,19896.0274,1989.60274,3905300,390.5300,39.05300,54123704,5412.3704,541.23704,...,1729,1.968824,1.721405,1.998844,3.374091,5.395232,2.236174,33.740906,53.952321,22.361736
14,2019,199985833,19998.5833,1999.85833,3922647,392.2647,39.22647,54253924,5425.3924,542.53924,...,1773,2.002016,1.676370,2.013221,3.177625,4.991527,2.105101,31.776251,49.915274,21.051012
15,2020,201011393,20101.1393,2010.11393,3939993,393.9993,39.39993,54384143,5438.4143,543.84143,...,1785,2.404417,1.964516,2.473606,3.341950,4.637064,2.136836,33.419499,46.370641,21.368361
16,2021,202036952,20203.6952,2020.36952,3957340,395.7340,39.57340,54514362,5451.4362,545.14362,...,1805,2.372290,2.222947,2.547174,3.249208,4.308450,2.149342,32.492076,43.084496,21.493419
17,2022,203062512,20306.2512,2030.62512,3974687,397.4687,39.74687,54644582,5464.4582,546.44582,...,1990,1.972568,1.923833,2.057430,3.211868,3.939933,2.209368,32.118681,39.399329,22.093682

In [55]:
dados.columns

Index(['ANO', 'POP_BR', 'POP_BR_10K', 'POP_BR_100K', 'POP_PB', 'POP_PB_10K',
       'POP_PB_100K', 'POP_NE', 'POP_NE_10K', 'POP_NE_100K', 'CAPES_CTI_BR',
       'CAPES_OUTRAS_BR', 'CAPES_CTI_PB', 'CAPES_OUTRAS_PB', 'CAPES_CTI_NE',
       'CAPES_OUTRAS_NE', 'CNPQ_MES_DOC_BR', 'CNPQ_MES_DOC_PB',
       'CNPQ_MES_DOC_NE', 'CNPQ_PQ_BR', 'CNPQ_PQ_PB', 'CNPQ_PQ_NE',
       'cti/outras_br', 'cti/outras_pb', 'cti/outras_ne', 'bolsas/pop10_BR',
       'bolsas/pop10_PB', 'bolsas/pop10_NE', 'bolsas/pop100_BR',
       'bolsas/pop100_PB', 'bolsas/pop100_NE', 'bolsas_pq/pop10_br',
       'bolsas_pq/pop10_pb', 'bolsas_pq/pop10_ne', 'bolsas_pq/pop100_br',
       'bolsas_pq/pop100_pb', 'bolsas_pq/pop100_ne'],
      dtype='object')

In [53]:
dados.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/new_data.xlsx", index = False)

In [57]:
dados["bolsas_pq/pop10_br"] = dados["CNPQ_PQ_BR"] / dados["POP_BR_10K"]
dados["bolsas_pq/pop10_pb"]= dados["CNPQ_PQ_PB"] / dados["POP_PB_10K"]
dados["bolsas_pq/pop10_ne"] = dados["CNPQ_PQ_NE"] / dados["POP_NE_10K"]

dados["bolsas_pq/pop100_br"] = dados["CNPQ_PQ_BR"] / dados["POP_BR_100K"]
dados["bolsas_pq/pop100_pb"] = dados["CNPQ_PQ_PB"] / dados["POP_PB_100K"]
dados["bolsas_pq/pop100_ne"] = dados["CNPQ_PQ_NE"] / dados["POP_NE_100K"]

dados["bolsas_md/pop10_br"] = dados["CNPQ_MES_DOC_BR"] / dados["POP_BR_10K"]
dados["bolsas_md/pop10_pb"]= dados["CNPQ_MES_DOC_BR"] / dados["POP_PB_10K"]
dados["bolsas_md/pop10_ne"] = dados["CNPQ_MES_DOC_BR"] / dados["POP_NE_10K"]

dados["bolsas_md/pop100_br"] = dados["CNPQ_MES_DOC_BR"] / dados["POP_BR_100K"]
dados["bolsas_md/pop100_pb"] = dados["CNPQ_MES_DOC_BR"] / dados["POP_PB_100K"]
dados["bolsas_md/pop100_ne"] = dados["CNPQ_MES_DOC_BR"] / dados["POP_NE_100K"]

dados.to_excel("/Users/pedroafmelo/Documents/projetos/sidtec_pb/etapa_2/pessoas_recursos/dados/new_data.xlsx")

# DADOS CURSOS CENSO SUPERIOR INEP